// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPuntoNET.Data;

#nullable disable

namespace ProyectoPuntoNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027202637_sqlite_migration_976")]
    partial class sqlite_migration_976
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProyectoPuntoNET.Data.Atleta", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Numero");

                    b.HasIndex("EventoId");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Data.ChipEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AtletaNumero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checkpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtletaNumero");

                    b.ToTable("ChipEvents");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Data.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Data.Atleta", b =>
                {
                    b.HasOne("ProyectoPuntoNET.Data.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Data.ChipEvent", b =>
                {
                    b.HasOne("ProyectoPuntoNET.Data.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaNumero");

                    b.Navigation("Atleta");
                });
#pragma warning restore 612, 618
        }
    }
}
