// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPuntoNET.Data;

#nullable disable

namespace ProyectoPuntoNET.Migrations
{
    [DbContext(typeof(ProyectoPuntoNETContext))]
    partial class ProyectoPuntoNETContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("ProyectoPuntoNET.Model.Atleta", b =>
                {
                    b.Property<int>("idAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("discapacidades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idAtleta");

                    b.ToTable("Atleta");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Model.Carrera", b =>
                {
                    b.Property<int>("idCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadPuntosControl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cuposDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("mapa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idCarrera");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Model.Participacion", b =>
                {
                    b.Property<int>("idParticipacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("atletaidAtleta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("carreraidCarrera")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("tiempoFinal")
                        .HasColumnType("TEXT");

                    b.Property<string>("tiempos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idParticipacion");

                    b.HasIndex("atletaidAtleta");

                    b.HasIndex("carreraidCarrera");

                    b.ToTable("Participacion");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Model.Participacion", b =>
                {
                    b.HasOne("ProyectoPuntoNET.Model.Atleta", "atleta")
                        .WithMany("participaciones")
                        .HasForeignKey("atletaidAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoPuntoNET.Model.Carrera", "carrera")
                        .WithMany("corredores")
                        .HasForeignKey("carreraidCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("atleta");

                    b.Navigation("carrera");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Model.Atleta", b =>
                {
                    b.Navigation("participaciones");
                });

            modelBuilder.Entity("ProyectoPuntoNET.Model.Carrera", b =>
                {
                    b.Navigation("corredores");
                });
#pragma warning restore 612, 618
        }
    }
}
