// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruevaDB1.Data;

#nullable disable

namespace pruevaDB1.Migrations
{
    [DbContext(typeof(pruevaDB1Context))]
    [Migration("20251114004035_Migra3")]
    partial class Migra3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Property<int>("IdAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtleta"));

                    b.Property<int>("ChipID")
                        .HasColumnType("int");

                    b.Property<string>("Discapacidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDorsal")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAtleta");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<int>("Cupos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantSensores")
                        .HasColumnType("int");

                    b.Property<int>("inscGanador")
                        .HasColumnType("int");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDorsal")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoTotal")
                        .HasColumnType("time");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("AtletaId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiempoParcial", b =>
                {
                    b.Property<int>("IdTiempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiempo"));

                    b.Property<int>("ChipID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraPaso")
                        .HasColumnType("time");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDorsal")
                        .HasColumnType("int");

                    b.Property<int>("Puesto")
                        .HasColumnType("int");

                    b.HasKey("IdTiempo");

                    b.HasIndex("InscripcionId");

                    b.ToTable("TiempoParcial");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Atleta", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruevaDB1.Components.Model.Carrera", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiempoParcial", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Inscripcion", "Inscripcion")
                        .WithMany("TiemposParciales")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.Navigation("TiemposParciales");
                });
#pragma warning restore 612, 618
        }
    }
}
