// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruevaDB1.Data;

#nullable disable

namespace pruevaDB1.Migrations
{
    [DbContext(typeof(pruevaDB1Context))]
    [Migration("20251104201914_Migra1")]
    partial class Migra1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Property<int>("IdAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtleta"));

                    b.Property<string>("Discapacidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAtleta");

                    b.ToTable("Atleta");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("Atleta")
                        .HasColumnType("int");

                    b.Property<int?>("AtletaIdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("Carrera")
                        .HasColumnType("int");

                    b.Property<int?>("CarreraIdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDorsal")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("AtletaIdAtleta");

                    b.HasIndex("CarreraIdCarrera");

                    b.ToTable("Participacion");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntosdeControl", b =>
                {
                    b.Property<int>("IdPunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPunto"));

                    b.Property<int>("CarreraIdIdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdPunto");

                    b.HasIndex("CarreraIdIdCarrera");

                    b.ToTable("PuntosdeControl");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiemposParciales", b =>
                {
                    b.Property<int>("IdTiempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiempo"));

                    b.Property<DateTime>("HoraPaso")
                        .HasColumnType("datetime2");

                    b.Property<int>("InscripcionIdIdInscripcion")
                        .HasColumnType("int");

                    b.Property<int>("PuntoControlIdIdPunto")
                        .HasColumnType("int");

                    b.HasKey("IdTiempo");

                    b.HasIndex("InscripcionIdIdInscripcion");

                    b.HasIndex("PuntoControlIdIdPunto");

                    b.ToTable("TiemposParciales");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Atleta", null)
                        .WithMany("Participaciones")
                        .HasForeignKey("AtletaIdAtleta");

                    b.HasOne("pruevaDB1.Components.Model.Carrera", null)
                        .WithMany("Corredores")
                        .HasForeignKey("CarreraIdCarrera");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntosdeControl", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Carrera", "CarreraId")
                        .WithMany("PuntosControl")
                        .HasForeignKey("CarreraIdIdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraId");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiemposParciales", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Inscripcion", "InscripcionId")
                        .WithMany("TiempoParcial")
                        .HasForeignKey("InscripcionIdIdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruevaDB1.Components.Model.PuntosdeControl", "PuntoControlId")
                        .WithMany("Tiempos")
                        .HasForeignKey("PuntoControlIdIdPunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionId");

                    b.Navigation("PuntoControlId");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Navigation("Corredores");

                    b.Navigation("PuntosControl");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Inscripcion", b =>
                {
                    b.Navigation("TiempoParcial");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntosdeControl", b =>
                {
                    b.Navigation("Tiempos");
                });
#pragma warning restore 612, 618
        }
    }
}
