// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruevaDB1.Data;

#nullable disable

namespace pruevaDB1.Migrations
{
    [DbContext(typeof(pruevaDB1Context))]
    partial class pruevaDB1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Property<int>("IdAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtleta"));

                    b.Property<string>("Discapacidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAtleta");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntoControl", b =>
                {
                    b.Property<int>("IdPunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPunto"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdPunto");

                    b.HasIndex("CarreraId");

                    b.ToTable("PuntosDeControl");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiempoParcial", b =>
                {
                    b.Property<int>("IdTiempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiempo"));

                    b.Property<DateTime>("HoraPaso")
                        .HasColumnType("datetime2");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("PuntoControlId")
                        .HasColumnType("int");

                    b.HasKey("IdTiempo");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("PuntoControlId");

                    b.ToTable("TiemposParciales");
                });

            modelBuilder.Entity("pruevaDB1.Data.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDorsal")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("AtletaId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntoControl", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Carrera", "Carrera")
                        .WithMany("PuntosDeControl")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.TiempoParcial", b =>
                {
                    b.HasOne("pruevaDB1.Data.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("pruevaDB1.Components.Model.PuntoControl", "PuntoControl")
                        .WithMany("TiemposParciales")
                        .HasForeignKey("PuntoControlId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("PuntoControl");
                });

            modelBuilder.Entity("pruevaDB1.Data.Models.Inscripcion", b =>
                {
                    b.HasOne("pruevaDB1.Components.Model.Atleta", "Atleta")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pruevaDB1.Components.Model.Carrera", "Carrera")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Atleta", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.Carrera", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("PuntosDeControl");
                });

            modelBuilder.Entity("pruevaDB1.Components.Model.PuntoControl", b =>
                {
                    b.Navigation("TiemposParciales");
                });
#pragma warning restore 612, 618
        }
    }
}
